/* Q1*/

SELECT 
 TR.TRACKID
,TR.Name AS TRACK_NAME
,AR.NAME AS ARTIST_NAME
,TR.COMPOSER
,GN.NAME AS GENRE_NAME
FROM 
 TRACKS  TR
,GENRES  GN
,ALBUMS  AB
,ARTISTS AR
WHERE TR.ALBUMID  = AB.ALBUMID
  AND AB.ARTISTID = AR.ARTISTID
  AND TR.GENREID  = GN.GENREID;

/* Q2 */

SELECT 
 CU.CUSTOMERID 
,CU.FIRSTNAME ||' '|| CU.LASTNAME AS FULL_NAME
,CU.PHONE
,CU.EMAIL
,CU.ADDRESS
||', '||CU.CITY
||', '||CU.STATE
||', '||CU.COUNTRY
||', Postal code: '||CU.POSTALCODE AS FULL_ADDRESS
,(SELECT COUNT(1)  
    FROM INVOICES IV
   WHERE IV.CUSTOMERID = CU.CUSTOMERID ) AS PURCHASES
FROM CUSTOMERS CU;


/* Q3 */

SELECT 
 CU.COUNTRY 
,SUBSTR(CU.EMAIL,INSTR(CU.EMAIL,'@')+1) AS DOMAIN
,COUNT( SUBSTR(CU.EMAIL,INSTR(CU.EMAIL,'@')+1)) AS COUNT_EMAILS_BY_DOMAINS
FROM  CUSTOMERS CU
GROUP BY 
 CU.COUNTRY 
,SUBSTR(CU.EMAIL,INSTR(CU.EMAIL,'@')+1)
;


/* Q4 */

SELECT 
 CU.COUNTRY
,(SELECT COUNT(DISTINCT TR.ALBUMID)  
FROM INVOICES      IV
    ,INVOICE_ITEMS IT
    ,TRACKS        TR 
WHERE IV.INVOICEID  = IT.INVOICEID
  AND IV.CUSTOMERID = CU.CUSTOMERID 
  AND TR.TRACKID    = IT.TRACKID 
) AS ALBUMS_PURCHASES
FROM  CUSTOMERS CU
GROUP BY 
 CU.COUNTRY
;


/* Q5 */

WITH COUNTRIES_ALBUMS AS
(
SELECT 
 CU.COUNTRY
,TR.ALBUMID
,COUNT(IT.INVOICEID) AS COUNT_INVOICEID
FROM CUSTOMERS     CU
    ,INVOICES      IV
    ,INVOICE_ITEMS IT
    ,TRACKS        TR 
WHERE IV.INVOICEID  = IT.INVOICEID
  AND IV.CUSTOMERID = CU.CUSTOMERID 
  AND TR.TRACKID    = IT.TRACKID 
GROUP BY 
 CU.COUNTRY
,TR.ALBUMID
)
,COUNTRIES_ALBUMS_MAX AS 
(SELECT 
 CA.COUNTRY
,MAX(CA.COUNT_INVOICEID) AS MAX_INVOICEID
FROM COUNTRIES_ALBUMS CA 
GROUP BY 
 CA.COUNTRY
)
SELECT 
CA.COUNTRY
,(SELECT AB.TITLE 
   FROM ALBUMS AB
  WHERE AB.ALBUMID = CA.ALBUMID ) AS ALBUM_NAME
,CA.COUNT_INVOICEID AS ALBUM_PURCHASES
FROM COUNTRIES_ALBUMS CA
WHERE  
(SELECT 1 
  FROM COUNTRIES_ALBUMS_MAX CM
  WHERE CM.COUNTRY = CA.COUNTRY
  AND  CM.MAX_INVOICEID = CA.COUNT_INVOICEID
);

/* Q6 */

SELECT 
 IV.BillingCountry AS COUNTRY
,TR.ALBUMID
,(SELECT AB.TITLE 
   FROM ALBUMS AB
  WHERE AB.ALBUMID = TR.ALBUMID ) AS ALBUM_NAME
,COUNT(IT.INVOICEID) AS ALBUM_PURCHASES
FROM INVOICES      IV
    ,INVOICE_ITEMS IT
    ,TRACKS        TR 
WHERE IV.INVOICEID  = IT.INVOICEID
  AND TR.TRACKID    = IT.TRACKID 
  AND IV.BillingCountry = 'USA'
  AND IV.INVOICEDATE >=   datetime('2011-01-01 00:00:00')-- DATE('2011-01-01','YYYY-MM-DD')
GROUP BY 
 IV.BillingCountry
,TR.ALBUMID
ORDER BY 
 IV.BillingCountry 
,COUNT(IT.INVOICEID) DESC
 LIMIT 1;

/* Q7 */

SELECT 
 CU.CUSTOMERID 
,CU.FIRSTNAME ||' '|| CU.LASTNAME AS FULL_NAME
,TRIM((CASE WHEN CU.FIRSTNAME  IS NULL THEN 'FIRSTNAME ' ELSE ' ' END )
||(CASE WHEN CU.LASTNAME   IS NULL THEN 'LASTNAME '      ELSE ' ' END )
||(CASE WHEN CU.PHONE      IS NULL THEN 'PHONE '         ELSE ' ' END )
||(CASE WHEN CU.EMAIL      IS NULL THEN 'EMAIL '         ELSE ' ' END )
||(CASE WHEN CU.COMPANY    IS NULL THEN 'COMPANY '       ELSE ' ' END )
||(CASE WHEN CU.ADDRESS    IS NULL THEN 'ADDRESS '       ELSE ' ' END )
||(CASE WHEN CU.CITY       IS NULL THEN 'CITY '          ELSE ' ' END )
||(CASE WHEN CU.STATE      IS NULL THEN 'STATE '         ELSE ' ' END )
||(CASE WHEN CU.COUNTRY    IS NULL THEN 'COUNTRY '       ELSE ' ' END )
||(CASE WHEN CU.POSTALCODE IS NULL THEN 'POSTALCODE'     ELSE ' ' END )
||(CASE WHEN CU.FAX        IS NULL THEN 'FAX '           ELSE ' ' END )) AS EMPTY_FIELDS
FROM CUSTOMERS CU
WHERE 
 (CASE WHEN CU.FIRSTNAME  IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.LASTNAME   IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.PHONE      IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.EMAIL      IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.COMPANY    IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.ADDRESS    IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.CITY       IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.STATE      IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.COUNTRY    IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.POSTALCODE IS NULL THEN 1 ELSE 0 END ) 
+(CASE WHEN CU.FAX        IS NULL THEN 1 ELSE 0 END ) >= 2
;